{% set name = "intake-xarray" %}
{% set version = "0.5.0" %}
{% set sha256 = "fa8166e7ef3e665d9b78e48ef74e9cb78e1bf2b2edc9c65278796336b07e8a24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake-xarray/intake-xarray-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask >=2.2
    - intake >=0.5.2
    - netcdf4
    - xarray >=0.12.0
    - zarr

test:
  imports:
    - intake_xarray

about:
  home: https://github.com/ContinuumIO/intake-xarray
  license: BSD-2-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: xarray plugins for Intake
